# Generated by Django 4.2.6 on 2023-11-27 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mangaweb.helper


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0002_remove_manga_likes_manga_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(null=True, upload_to=mangaweb.helper.user),
        ),
        migrations.AlterField(
            model_name='manga',
            name='likes',
            field=models.ManyToManyField(related_name='liked_manga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=256)),
                ('comment_likes', models.ManyToManyField(related_name='like_on_comment', to=settings.AUTH_USER_MODEL)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaweb.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
