# Generated by Django 4.2.6 on 2023-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0004_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
