# Generated by Django 4.2.6 on 2023-11-30 00:34

from django.db import migrations, models
import mangaweb.helper


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0007_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='thumb',
            field=models.ImageField(null=True, upload_to=mangaweb.helper.manga_thumb),
        ),
    ]
