# Generated by Django 4.2.6 on 2023-12-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0009_user_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
