# Generated by Django 4.2.6 on 2023-12-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0010_manga_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
