# Generated by Django 4.2.6 on 2023-12-04 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0011_manga_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='read',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manga',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_manga', to=settings.AUTH_USER_MODEL),
        ),
    ]
