# Generated by Django 4.2.6 on 2023-12-04 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0012_chapter_read_alter_manga_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='read',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
