# Generated by Django 4.2.6 on 2023-12-05 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0014_alter_chapter_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='views',
        ),
    ]
