# Generated by Django 4.2.6 on 2023-12-05 04:50

from django.db import migrations, models
import mangaweb.helper


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0015_remove_manga_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=mangaweb.helper.manga_thumb),
        ),
    ]
