# Generated by Django 4.2.6 on 2023-12-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0017_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='sinopse',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
