# Generated by Django 4.2.6 on 2023-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0018_manga_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='sinopse',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
