# Generated by Django 4.2.6 on 2023-12-09 08:32

from django.db import migrations, models
import mangaweb.helper


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0019_alter_manga_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=mangaweb.helper.user),
        ),
    ]
