# Generated by Django 4.2.6 on 2023-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0020_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending')], max_length=1),
        ),
    ]
