# Generated by Django 4.2.6 on 2023-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0022_alter_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restrained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Releasing'), ('N', 'Not released'), ('C', 'Check')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
