# Generated by Django 4.2.6 on 2023-12-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0023_user_restrained_alter_manga_status_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='restrained',
            new_name='retained',
        ),
    ]
