# Generated by Django 4.2.6 on 2023-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0024_rename_restrained_user_retained'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faults',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
