# Generated by Django 4.2.6 on 2023-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0025_user_faults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Releasing'), ('N', 'Not released'), ('R', 'Retained')], max_length=1),
        ),
    ]
