# Generated by Django 4.2.6 on 2023-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaweb', '0026_alter_manga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retain_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Releasing'), ('N', 'Not released'), ('A', 'Retained for analysis')], max_length=1),
        ),
    ]
